### ISSUE TITLE
Deprecation warnings with Ruby 2.2.1

### ISSUE THREAD

**Issue by mathiasAichinger** [normelton/snmp4em#6]
I'm getting the following deprecation warnings when using Ruby 2.2.2

`/Users/matchi/.rvm/gems/ruby-2.2.1/gems/snmp4em-1.1.2/lib/snmp4em/requests/snmp_walk_request.rb:29: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
/Users/matchi/.rvm/gems/ruby-2.2.1/gems/snmp4em-1.1.2/lib/snmp4em/requests/snmp_walk_request.rb:29: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
`

**Comment by normelton** [comment]
Interesting. It seems related to hallidave/ruby-snmp#35, which references https://bugs.ruby-lang.org/issues/7688. It also suggests a fix, which seems trivial, given that there doesn't seem to be much traction on the ruby-snmp side.

But I can't seem to recreate the warning. Can you provide your gem versions and some code that causes the message?

**Comment by normelton** [comment]
Close alongside #7
